# SSH authorization so that travis can push documentation to the repository.
env:
  global:
    secure: "FlkSAz9RcwQ8AAYkP9wrFTVZAuOAThAZEpMEykMgUAIaFaCoVptMC2DY/ZA8gaGO1+WCd4xa5cAshzIsSzlxB54SPZXjODWXORzQ4bmleYDsaD0O0MapWQctsx7J09XIqYYDThK3njK43cZQ/Dxw8vIQTVxNd4I3H50r6ACD2BinpTx7FTaI9taAWold20Vc04+paB93edBLXi1wIM+4C7f9z2obIuvJH7Hqiv/ks0D6rAHZBRPtTMCKPGcxBzCbNQCrEaAYrAp/M2tzQ+RQDrvqXtvW4ZIK6PRPJEpySGYdhGlKK2Q01/XL/5EpudM4HdcxQ/K949xJB1i17DKsPVyY0b4yaq9qPkfE/dF4QvACb2vIlTZILmiOc1cquuKzzXw8PBpV368nL8nho3i0ggRtOCwq2WSbAt5arhCyWrxSXUY9IqCeQGdOAci/+LogriyZN4juW1+kfi2P/J5Zz0E+hE3PhRyA+2duIqNfyCki9IHFQ72O0MNKuQWFAe228HCzThn9bEkTcLfcPxefGk5kEtSs57avB7bHi7cr4ulqQW6ltODHO0A3o1wTkSFdVTHUgU4B28ZsUfqO4ktNIlhYBberrSkbLdAPKWimrcBHkgV+XIOiIH0Jih6pv/BkN4UdkG2DPf3urplYm4D2Eym8GW3S8OtcnH5anZclBnI="

language: cpp

compiler:
  - gcc
  #- clang

os:
  - linux

branches:
  only:
    - master

notifications:
  email: false

install:
  - echo $TRAVIS_OS_NAME
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:tuleu/precise-backports; fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install --yes build-essential
    doxygen libgflags-dev libgoogle-glog-dev mercurial cmake libatlas-base-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install python-software-properties; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install gcc-4.8 g++-4.8; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --config gcc; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --config g++; fi

before_script:
  # Get Eigen. The apt-get version on 12.04 is too old; we need at least 3.1.0.
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then mkdir eigen && cd eigen; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then hg clone https://bitbucket.org/eigen/eigen; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd eigen && hg update 3.2; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then mkdir build && cd build; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cmake -DCMAKE_BUILD_TYPE=Release ..; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make -j4; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo make install; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd ../../..; fi

  # Configure and make.
  - mkdir bin
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script:
  - make -j4
  - ./run_tests

after_success:
  # Make and publish documentation.
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${PA_TOKEN}:@github.com" > .git/credentials
  - $(npm bin)/set-up-ssh --key "$encrypted_fb541bf77981_key" \
                          --iv "$encrypted_fb541bf77981_iv" \
                          --path-encrypted-key ".travis/github_deploy_key.enc"
  - make documentation
  - cd ..
  - ./documentation/publish_documentation.sh
